
language: node_js
sudo: false
dist: trusty
node_js:
  - "8"

services:
  - docker

cache:
  yarn: true
  directories:
    - "node_modules"

install:
  - yarn

before_deploy:
  - docker build -t openpitrix/website .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
    repo: openpitrix/website
